# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34dd844aa4f727bee84ce82b19b787b094bb2f4d49d24e637e8aa089fb27554f76f7400223d582744e764efb27d55ed9011d146ada1643b50c07bd53b3567c08

test:
  secret_key_base: eba2f752a2c8510a8b86119d6b7cd37b4218a8dbb4e482872ba2709c12cb61553a46544d3b99165097220f9376278527f63283fa5d3a18d7cb2b0cdb9f7e98b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
